// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {relay} from '../models';
import {main} from '../models';
import {daemon} from '../models';

export function AddRelayRule(arg1:string,arg2:string,arg3:string,arg4:number,arg5:number,arg6:boolean):Promise<void>;

export function AddRoute(arg1:string,arg2:number,arg3:string,arg4:string,arg5:string):Promise<void>;

export function CheckRelay():Promise<relay.CheckResult>;

export function CreateTunnel(arg1:string):Promise<void>;

export function DeleteCloudTunnel(arg1:string):Promise<void>;

export function DestroyTunnel():Promise<void>;

export function FollowLog(arg1:string):Promise<void>;

export function GetRelay():Promise<main.RelayInfo>;

export function GetState():Promise<main.StateInfo>;

export function ListRoutes():Promise<Array<main.RouteInfo>>;

export function ListTunnels():Promise<Array<main.TunnelInfo>>;

export function LogDir():Promise<string>;

export function OpenPath(arg1:string):Promise<void>;

export function RelayDown():Promise<void>;

export function RelayUp():Promise<void>;

export function RemoveRelayRule(arg1:string):Promise<void>;

export function RemoveRoute(arg1:string):Promise<void>;

export function RunDiagnose():Promise<daemon.DiagnoseResult>;

export function SaveAuth(arg1:string,arg2:string):Promise<void>;

export function SaveRelayServer(arg1:string,arg2:string):Promise<void>;

export function StartFast(arg1:number,arg2:boolean,arg3:string,arg4:string,arg5:string):Promise<void>;

export function StopFast():Promise<void>;

export function SyncIngress():Promise<void>;

export function TailLog(arg1:string,arg2:number):Promise<Array<string>>;

export function TunnelDown():Promise<void>;

export function TunnelUp():Promise<void>;

export function UnfollowLog(arg1:string):Promise<void>;
