// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddRelayRule(arg1, arg2, arg3, arg4, arg5, arg6) {
  return window['go']['main']['App']['AddRelayRule'](arg1, arg2, arg3, arg4, arg5, arg6);
}

export function AddRoute(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['AddRoute'](arg1, arg2, arg3, arg4, arg5);
}

export function CheckRelay() {
  return window['go']['main']['App']['CheckRelay']();
}

export function CreateTunnel(arg1) {
  return window['go']['main']['App']['CreateTunnel'](arg1);
}

export function DeleteCloudTunnel(arg1) {
  return window['go']['main']['App']['DeleteCloudTunnel'](arg1);
}

export function DestroyTunnel() {
  return window['go']['main']['App']['DestroyTunnel']();
}

export function FollowLog(arg1) {
  return window['go']['main']['App']['FollowLog'](arg1);
}

export function GetRelay() {
  return window['go']['main']['App']['GetRelay']();
}

export function GetState() {
  return window['go']['main']['App']['GetState']();
}

export function ListRoutes() {
  return window['go']['main']['App']['ListRoutes']();
}

export function ListTunnels() {
  return window['go']['main']['App']['ListTunnels']();
}

export function LogDir() {
  return window['go']['main']['App']['LogDir']();
}

export function OpenPath(arg1) {
  return window['go']['main']['App']['OpenPath'](arg1);
}

export function RelayDown() {
  return window['go']['main']['App']['RelayDown']();
}

export function RelayUp() {
  return window['go']['main']['App']['RelayUp']();
}

export function RemoveRelayRule(arg1) {
  return window['go']['main']['App']['RemoveRelayRule'](arg1);
}

export function RemoveRoute(arg1) {
  return window['go']['main']['App']['RemoveRoute'](arg1);
}

export function RunDiagnose() {
  return window['go']['main']['App']['RunDiagnose']();
}

export function SaveAuth(arg1, arg2) {
  return window['go']['main']['App']['SaveAuth'](arg1, arg2);
}

export function SaveRelayServer(arg1, arg2) {
  return window['go']['main']['App']['SaveRelayServer'](arg1, arg2);
}

export function StartFast(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['StartFast'](arg1, arg2, arg3, arg4, arg5);
}

export function StopFast() {
  return window['go']['main']['App']['StopFast']();
}

export function SyncIngress() {
  return window['go']['main']['App']['SyncIngress']();
}

export function TailLog(arg1, arg2) {
  return window['go']['main']['App']['TailLog'](arg1, arg2);
}

export function TunnelDown() {
  return window['go']['main']['App']['TunnelDown']();
}

export function TunnelUp() {
  return window['go']['main']['App']['TunnelUp']();
}

export function UnfollowLog(arg1) {
  return window['go']['main']['App']['UnfollowLog'](arg1);
}
